import { expect, test } from 'vitest'
import * as exportedNameSpaces from './index'

test('exports', () => {
  expect(Object.keys(exportedNameSpaces)).toMatchInlineSnapshot(`
    [
      "BIG_INT_TEN",
      "BIPS_BASE",
      "MIN_BNB",
      "BETTER_TRADE_LESS_HOPS_THRESHOLD",
      "SMART_ROUTER_ADDRESSES",
      "BASES_TO_CHECK_TRADES_AGAINST",
      "ADDITIONAL_BASES",
      "CUSTOM_BASES",
      "COST_PER_UNINIT_TICK",
      "BASE_SWAP_COST_V3",
      "COST_PER_INIT_TICK",
      "COST_PER_HOP_V3",
      "usdGasTokensByChain",
      "BATCH_MULTICALL_CONFIGS",
      "MSG_SENDER",
      "ADDRESS_THIS",
      "V3_QUOTER_ADDRESSES",
      "SmartRouter",
      "SwapRouter",
      "Transformer",
      "PoolType",
      "RouteType",
    ]
  `)
})

test('SmartRouter exports', () => {
  expect(Object.keys(exportedNameSpaces.SmartRouter)).toMatchInlineSnapshot(`
    [
      "getBestTrade",
      "v3PoolSubgraphSelection",
      "getV3PoolsWithoutTicksOnChain",
      "getV3PoolSubgraph",
      "getAllV3PoolsFromSubgraph",
      "v3PoolTvlSelector",
      "createHybridPoolProvider",
      "createStaticPoolProvider",
      "v3PoolsOnChainProviderFactory",
      "getV3PoolsWithTvlFromOnChain",
      "getV3PoolsWithTvlFromOnChainFallback",
      "getV3PoolsWithTvlFromOnChainStaticFallback",
      "createGetV3CandidatePoolsWithFallbacks",
      "createGetV3CandidatePools",
      "getV3CandidatePools",
      "getCandidatePools",
      "createPoolProvider",
      "createQuoteProvider",
      "createOffChainQuoteProvider",
      "PancakeMulticallProvider",
      "createCommonTokenPriceProvider",
      "getTokenUsdPricesBySubgraph",
      "getCommonTokenPricesBySubgraph",
      "getCommonTokenPricesByLlma",
      "getCommonTokenPricesByWalletApi",
      "getCommonTokenPrices",
      "getExecutionPrice",
      "maximumAmountIn",
      "minimumAmountOut",
      "isV3Pool",
      "getMidPrice",
      "involvesCurrency",
      "metric",
      "log",
      "Transformer",
      "getPoolAddress",
      "getPairCombinations",
      "getCheckAgainstBaseTokens",
      "APISchema",
    ]
  `)
})
